CREATE TABLE Usuario (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR2(50) NOT NULL UNIQUE,
    password_hash VARCHAR2(150) NOT NULL
);

CREATE TABLE Grupo (
    id NUMBER(10) GENERATED BY DEFAULT AS IDENTITY (START WITH 1 INCREMENT BY 1) PRIMARY KEY,
    nombre VARCHAR2(50 CHAR) NOT NULL,
    cod_invitacion VARCHAR2(6 CHAR) NOT NULL UNIQUE,
    creador NUMBER(10) NOT NULL,
    torneo_id NUMBER(10) NOT NULL,
    max_apuestas NUMBER(3) DEFAULT 1 NOT NULL,
    CONSTRAINT chk_max_apuestas CHECK (max_apuestas >= 1),
    CONSTRAINT fk_grupo_creador FOREIGN KEY (creador) REFERENCES Usuario(id),
    CONSTRAINT fk_grupo_torneo FOREIGN KEY (torneo_id) REFERENCES Torneo(id)
);

CREATE TABLE Miembro (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    usuario_id NUMBER NOT NULL,
    grupo_id NUMBER NOT NULL,
    rol VARCHAR2(10) NOT NULL,
    UNIQUE (usuario_id, grupo_id),
    FOREIGN KEY (usuario_id) REFERENCES Usuario(id),
    FOREIGN KEY (grupo_id) REFERENCES Grupo(id)
);

CREATE TABLE Torneo (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR2(50) NOT NULL,
    anyo NUMBER NOT NULL,
    id_externo_api VARCHAR2(50) NOT NULL,
    fecha_ini DATE NOT NULL,
    fecha_fin DATE NOT NULL,
    UNIQUE (nombre, anyo)
);

CREATE TABLE Partido (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_torneo NUMBER NOT NULL,
    id_externo_api VARCHAR2(50) UNIQUE,
    equipo_local VARCHAR2(50) NOT NULL,
    equipo_visitante VARCHAR2(50) NOT NULL,
    fecha_hora_utc DATE NOT NULL,
    res_local NUMBER,
    res_visit NUMBER,
    FOREIGN KEY (id_torneo) REFERENCES Torneo(id)
);

CREATE TABLE Pronostico (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id NUMBER NOT NULL,
    partido_id NUMBER NOT NULL,
    goles_local NUMBER NOT NULL,
    goles_visit NUMBER NOT NULL,
    puntos NUMBER NOT NULL,
    fecha_create DATE NOT NULL,
    fecha_mod DATE,
    UNIQUE (user_id, partido_id),
    FOREIGN KEY (user_id) REFERENCES Usuario(id),
    FOREIGN KEY (partido_id) REFERENCES Partido(id)
);

CREATE TABLE ReglasPuntuacionGlobales (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    exact_result NUMBER NOT NULL,
    puntos_winner NUMBER NOT NULL
);
